version: '2'

services:
  front:
    image: rootpia/mnist_front:latest
    container_name: front
    depends_on:
      - ai
    ports:
      - "55000:80"
    environment:
      - MNIST_API_IP=ai
      - RECOGNITION_NUM=1

  batch:
    image: rootpia/mnist_batch:latest
    container_name: batch
    depends_on:
      - ai
    ports:
      - "56000:80"
    environment:
      - MNIST_API_IP=ai

  ai:
    image: rootpia/mnist_ai:latest
    container_name: ai
