version: '2'

services:
  front:
    image: rootpia/mnist_front:latest
    container_name: front
    depends_on:
      - ai
      - db
    ports:
      - "55000:80"
    environment:
      - MNIST_API_IP=ai

  batch:
    image: rootpia/mnist_batch:latest
    container_name: batch
    depends_on:
      - ai
    ports:
      - "56000:80"
    environment:
      - MNIST_API_IP=ai

  ai:
    image: rootpia/mnist_ai:latest
    container_name: ai
    environment:
      - RECOGNITION_NUM=1

  db:
    image: redis
    container_name: db
    volumes:
      - ./data/redis:/data
    command:
      redis-server --appendonly yes

